version: 0.2

phases: 
    install:
        runtime-versions:
            python: 3.9
        commands:
            - pip install pytest
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - python -m pytest --junitxml=test_results.xml
    post_build:
        commands:
            - echo "we are in the post build phase"

reports:
    pytest_reports:
        files:
            - test_results.xml
        base-directory: ./test
        file-format: JUNITXML
